<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 ./tiktak.glb -t
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { interactivity, useGltf } from '@threlte/extras';
	import { spring } from 'svelte/motion';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Cube: THREE.Mesh;
			board: THREE.Mesh;
			Cube002: THREE.Mesh;
			Cube003: THREE.Mesh;
			Cube004: THREE.Mesh;
			Cube005: THREE.Mesh;
			Cube006: THREE.Mesh;
			Cube007: THREE.Mesh;
			Cube008: THREE.Mesh;
			Cube009: THREE.Mesh;
		};
		materials: {
			['Material.005']: THREE.MeshStandardMaterial;
			['Material.004']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/tiktak.glb');

	const component = forwardEventHandlers();

	interactivity();
	let position1 = spring(1.52);
	let position2 = spring(1.52);
	let position3 = spring(1.52);
	let position4 = spring(1.52);
	let position5 = spring(1.52);
	let position6 = spring(1.52);
	let position7 = spring(1.52);
	let position8 = spring(1.52);
	let position9 = spring(1.52);
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Cube.geometry}
			material={gltf.materials['Material.005']}
			position={[0, 1.52, 0]}
			scale={[1, 0.26, 1]}
			on:click={() => {
				position1.set(1.72);
			}}
			on:mouseenter={() => {
				position1.set(1.4);
			}}
			on:mouseleave={() => {
				position1.set(1.52);
			}}
			on:pointerleave={() => {
				position1.set(1.52);
			}}
			on:pointerenter={() => {
				position1.set(1.4);
			}}
			position.y={$position1}
		/>
		<T.Mesh
			geometry={gltf.nodes.board.geometry}
			material={gltf.materials['Material.004']}
			position={[0, 2.25, 0]}
			scale={[5.12, 0.34, 5.12]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube002.geometry}
			material={gltf.materials['Material.005']}
			position={[3.24, 1.52, 0]}
			scale={[1, 0.26, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube003.geometry}
			material={gltf.materials['Material.005']}
			position={[-3.18, 1.52, 0]}
			scale={[1, 0.26, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube004.geometry}
			material={gltf.materials['Material.005']}
			position={[0, 1.52, 3.04]}
			scale={[1, 0.26, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube005.geometry}
			material={gltf.materials['Material.005']}
			position={[3.24, 1.52, 3.04]}
			scale={[1, 0.26, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube006.geometry}
			material={gltf.materials['Material.005']}
			position={[-3.18, 1.52, 3.04]}
			scale={[1, 0.26, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube007.geometry}
			material={gltf.materials['Material.005']}
			position={[0, 1.52, -3.05]}
			scale={[1, 0.26, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube008.geometry}
			material={gltf.materials['Material.005']}
			position={[3.24, 1.52, -3.05]}
			scale={[1, 0.26, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube009.geometry}
			material={gltf.materials['Material.005']}
			position={[-3.18, 1.52, -3.05]}
			scale={[1, 0.26, 1]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
