<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.0-next.12 ./tiktak.glb -t
-->

<script lang="ts">
	import type * as THREE from 'three';
	import { Group } from 'three';
	import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core';
	import { interactivity, useGltf } from '@threlte/extras';
	import { spring } from 'svelte/motion';

	type $$Props = Props<THREE.Group>;
	type $$Events = Events<THREE.Group>;
	type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } };

	export const ref = new Group();

	type GLTFResult = {
		nodes: {
			Cube: THREE.Mesh;
			Cube001: THREE.Mesh;
			tiktakCube: THREE.Mesh;
			Text: THREE.Mesh;
			Text001: THREE.Mesh;
		};
		materials: {
			Material: THREE.MeshStandardMaterial;
			['Material.001']: THREE.MeshStandardMaterial;
		};
	};

	const gltf = useGltf<GLTFResult>('/tiktak.glb');
	interactivity();
	let scale = spring(0, { stiffness: 0.2, damping: 0.5 });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.Cube.geometry}
			material={gltf.materials.Material}
			on:click={() => {
				scale.set(1.2);
				setTimeout(() => {
					scale.set(0);
				}, 1000);
			}}
			on:pointerleave={() => {
				scale.set(0);
			}}
			on:pointerenter={() => {
				scale.set(-0.2);
			}}
			position.y={$scale}
		/>
		<T.Mesh
			geometry={gltf.nodes.Cube001.geometry}
			material={gltf.materials.Material}
			position={[0, 2.52, 0]}
			scale={[1.78, 0.1, 1.78]}
		/>
		<T.Mesh
			geometry={gltf.nodes.tiktakCube.geometry}
			material={gltf.materials['Material.001']}
			position={[0, 2.62, 3.56]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[1.29, 0.1, 1.29]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Text.geometry}
			material={gltf.materials.Material}
			position={[-0.29, 4.69, 3.45]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Text001.geometry}
			material={gltf.materials['Material.001']}
			position={[-0.29, 4.69, 0.4]}
			on:click={() => {
				scale.set(1.2);
			}}
			on:pointerleave={() => {
				scale.set(0);
			}}
			on:pointerenter={() => {
				scale.set(-0.2);
			}}
			position.y={$scale + 4.69}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
